# Generated by Django 5.2.4 on 2025-10-10 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='dashboard.coursemodule'),
        ),
        migrations.CreateModel(
            name='MaterialDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='dashboard.coursematerial')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_downloads', to='dashboard.student')),
            ],
            options={
                'verbose_name_plural': 'Material Downloads',
                'unique_together': {('student', 'material')},
            },
        ),
    ]
