# Generated by Django 5.2.3 on 2025-10-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_coursematerial_is_required_coursematerial_module_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursematerial',
            name='is_required',
        ),
        migrations.RemoveField(
            model_name='coursematerial',
            name='module',
        ),
    ]
