# Generated by Django 5.2.3 on 2025-10-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_coursematerial_is_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='assignment_attachments/%Y/%m/%d/', verbose_name='Assignment Files'),
        ),
    ]
