# Generated by Django 5.2.3 on 2025-09-15 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_userprofile'),
        ('dashboard', '0005_course_created_at'),
    ]

    operations = [
    ]
