# Generated by Django 5.2.3 on 2025-09-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_merge_0003_userprofile_0005_course_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='students', to='dashboard.course'),
        ),
    ]
