# Generated by Django 5.2.4 on 2025-09-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_userprofile_bio_userprofile_theme_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/%Y/%m/%d/'),
        ),
    ]
