# Generated by Django 5.2.4 on 2025-10-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_submission_comments_coursemodule_studentprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
