# Generated by Django 5.2.4 on 2025-10-09 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_coursemodule_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='dashboard.coursemodule'),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='completed_modules',
            field=models.ManyToManyField(blank=True, related_name='completed_by', to='dashboard.coursemodule'),
        ),
        migrations.AlterUniqueTogether(
            name='studentprogress',
            unique_together={('student', 'course', 'module')},
        ),
    ]
